import Navigation from '@/components/Navigation';
import './globals.css'

export const metadata = {
  title: 'Learning to Create my first Next Application',
  description: 'Generated by create next app',
  keywords: 'next, react, app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href='https://bootswatch.com/5/spacelab/bootstrap.min.css' />
      </head>
      <body>
       <Navigation />
        <div className='container p-4' >{children}</div>
      </body>
    </html>
  );
}
